"""add price_alerts table

Revision ID: 964fdb8cab9a
Revises: f767d2c923a9
Create Date: 2026-06-19 07:41:01.801878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964fdb8cab9a'
down_revision: Union[str, Sequence[str], None] = 'f767d2c923a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notify_channel', sa.String(length=20), nullable=False),
    sa.Column('notify_target', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_destination'), 'price_alerts', ['destination'], unique=False)
    op.create_index(op.f('ix_price_alerts_origin'), 'price_alerts', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alerts_origin'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_destination'), table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
